// body.insertAdjacentHTML('beforeend', '<div class="container">'
//   + '<h1 class="title">Virtual keyboard</h1>'
//   + '<div class="container-text-keyboard">'
//   + '<div class="text-area-container">'
//   + '<textarea placeholder="Tap to start" class="input"></textarea>'
//   + '</div>'
//   + '<div class="keyboard-container">'
//   + '<ul class="first-row rows">'
//   + '<li>'
//   + '<span class="caseDown">`</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">1</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">2</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">3</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">4</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">5</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">6</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">7</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">8</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">9</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">0</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">-</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">=</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">delete</span>'
//   + '</li>'
//   + '</ul>'
//   + '<ul class="first-row rows">'
//   + '<li>'
//   + '<span class="caseDown">tab</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">q</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">w</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">e</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">r</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">t</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">y</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">u</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">i</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">o</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">[</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">]</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">&#x0002F;</span>'
//   + '</li>'
//   + '</ul>'
//   + '</ul>'
//   + '<ul class="first-row rows">'
//   + '<li>'
//   + '<span class="caseDown">caps lock</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">a</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">s</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">d</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">f</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">g</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">h</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">j</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">k</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">l</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">;</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">&#x00027;</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">return</span>'
//   + '</li>'
//   + '</ul>'
//   + '<ul class="first-row rows">'
//   + '<li>'
//   + '<span class="caseDown">shift</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">z</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">x</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">c</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">c</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">v</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">b</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">n</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">m</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">,</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">.</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">/</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">shift</span>'
//   + '</li>'
//   + '</ul>'
//   + '<ul class="first-row last-row rows">'
//   + '<li>'
//   + '<span class="">fn</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">⌃</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">⌥</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">⌘</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="space"></span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">⌘</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="">⌥</span>'
//   + '</li>'
//   + '<div class="arrow-container">'
//   + '<li class="caseUp">'
//   + '<span>&#x25B4;</span>'
//   + '</li>'
//   + '<div class="arrow">'
//   + '<li>'
//   + '<span class="caseLeft">&#x25C2;</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="caseDown">&#x25BE;</span>'
//   + '</li>'
//   + '<li>'
//   + '<span class="caseRight">&#x25B8;</span>'
//   + '</li>'
//   + '</div>'
//   + '</div>'
//   + '</ul>'
//   + '</div>'
//   + '</div>'
//   + '</div>'
//   + '<div class="description">'
//   + '<p>Keyboard was created for macOS</p>'
//   + '<p>Switch between languages: command (⌘) + space</p>'
//   + '</div>');
